version: '3.3'
services:
  database:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306"
    restart: always

  wordpress:
    depends_on:
      - database
    container_name: wordpress
    image: wordpress:latest 
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_PREFIX: wp_
    volumes:
       - ./wp-content:/var/www/html/wp-content
    ports:
      - "80:80"
    restart: always
  
networks:
  default:
    external:
      name: CSC_Network

#  nginx:
#    depends_on:
#      - wordpress
#    container_name: nginx
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#      - "443:433"

